# Generated by Django 6.0.2 on 2026-03-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('cooking', 'Готовится'), ('delivery', 'В пути'), ('delivered', 'Доставлен')], default='created', max_length=20),
        ),
    ]
