# Generated by Django 6.0.2 on 2026-03-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, help_text='От 0 до 5', max_digits=2, verbose_name='Рейтинг'),
        ),
    ]
