# Generated by Django 6.0.2 on 2026-03-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_add_product_rating_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_last_four',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Последние 4 цифры карты'),
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес доставки'),
        ),
    ]
